POST http://localhost:8081/user/signup
Content-Type: application/json

{
  "username": "PeterGriffin",
  "email": "petergriffin@gmail.com",
  "password": "hehehehe"
}

###
POST http://localhost:8081/user/login
Content-Type: application/json

{
  "username": "PeterGriffin",
  "password": "hehehehe"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###
POST http://localhost:8081/user/editUser
Content-Type: application/json

{
  "username": "Short",
  "email": "notanemail",
  "password": "short"
}

###
POST http://localhost:8081/user/editUser
Content-Type: application/json

{
  "username": "LoisGriffin",
  "email": "loisgriffin@gmail.com",
  "password": "peeeetah"
}

###
GET  http://localhost:8081/user/userInfo
Content-Type: application/json

###
POST http://localhost:8081/user/darkTheme
Content-Type: application/json

{
  "darkTheme": true
}

###
POST http://localhost:8081/favorites/new
Content-Type: application/json

{
  "route": "CR-Newburyport",
  "routeName": "Newburyport/Rockport Line"
}

###
POST http://localhost:8081/favorites/new
Content-Type: application/json

{
  "route": "CR-Newburyport",
  "routeName": "Newburyport/Rockport Line",
  "station": "place-ER-0168",
  "stationLatLng": [
    42.524792,
    -70.895876
  ],
  "stationName": "Salem"
}

###
GET  http://localhost:8081/favorites/68123be7147a4c26584bf462/68123bf5147a4c26584bf466
Content-Type: application/json

###
DELETE http://localhost:8081/favorites/68125a03402d9941df3cd550
Content-Type: application/json

### Get vehicles for a route
GET http://localhost:8081/api/vehicles/1
Content-Type: application/json

### Get trips for a route
GET http://localhost:8081/api/trips/67959825
Content-Type: application/json

### Get shape info by route ID
GET http://localhost:8081/api/shapes/933_0020
Content-Type: application/json

### Get all mbta routes
GET http://localhost:8081/api/routes/
Content-Type: application/json

### Get subway routes
GET http://localhost:8081/api/routes/1
Content-Type: application/json

### Get stops by route and date
GET http://localhost:8081/api/stops/2025-04-18/Orange
Content-Type: application/json

### Get all alerts
GET http://localhost:8081/api/alerts
Content-Type: application/json