POST http://localhost:8081/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

POST http://localhost:8081/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###
POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "67d4634b26893332736331b6",
    "username" : "Tochi Edit",
    "password" : "dwwrwr"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf1"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "67d4634b26893332736331b6"
}

###
POST  http://localhost:8081/favorite/newFavorite
Content-Type: application/json

{
    "ownerId" : "67d4634b26893332736331b6",
    "route" : "CR-Newburyport",
    "station" : "place-ER-0168"
}

###
GET  http://localhost:8081/favorite/getFavoriteById/67d4638626893332736331bd
Content-Type: application/json

###
POST http://localhost:8081/favorite/editFavorite
Content-Type: application/json

{
    "favoriteId" : "67d4638626893332736331bd",
    "ownerId" : "67d4634b26893332736331b6",
    "route" : "Red",
    "station" : "place-sstat"
}

###
POST  http://localhost:8081/user/deleteAll
Content-Type: application/json

###
POST  http://localhost:8081/favorite/deleteAllFavorite
Content-Type: application/json