POST http://localhost:8081/user/signup
Content-Type: application/json

{
  "username": "PeterGriffin",
  "email": "petergriffin@gmail.com",
  "password": "hehehehe"
}

###
POST http://localhost:8081/user/login
Content-Type: application/json

{
  "username": "PeterGriffin",
  "password": "hehehehe"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###
POST http://localhost:8081/user/editUser
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MGM2MGUzMzdmOWNiOTkwODAwYWEyMCIsImVtYWlsIjoicGV0ZXJncmlmZmluQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiUGV0ZXJHcmlmZmluIiwiaWF0IjoxNzQ1NjQxNzA3LCJleHAiOjE3NDgyMzM3MDd9.Mj9sINjvXKuiDjihFGXiEl6QbV5E58euvd0DJsBhmwE",
  "username": "Short",
  "email": "notanemail",
  "password": "tooshort"
}

###
POST http://localhost:8081/user/editUser
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MGM2MGUzMzdmOWNiOTkwODAwYWEyMCIsImVtYWlsIjoicGV0ZXJncmlmZmluQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiUGV0ZXJHcmlmZmluIiwiaWF0IjoxNzQ1NjQxNzA3LCJleHAiOjE3NDgyMzM3MDd9.Mj9sINjvXKuiDjihFGXiEl6QbV5E58euvd0DJsBhmwE",
  "username": "LoisGriffin",
  "email": "loisgriffin@gmail.com",
  "password": "peeeetah"
}

###
GET  http://localhost:8081/user/userInfo
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MGM2MGUzMzdmOWNiOTkwODAwYWEyMCIsImVtYWlsIjoibG9pc2dyaWZmaW5AZ21haWwuY29tIiwidXNlcm5hbWUiOiJMb2lzR3JpZmZpbiIsImlhdCI6MTc0NTY0MTkxMywiZXhwIjoxNzQ4MjMzOTEzfQ.F_eRz4sSZQNiy8_GwzXqpL6GNFd3vinggQKoi8tpfHI"
}

###
POST http://localhost:8081/favorites/new
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MGM2MGUzMzdmOWNiOTkwODAwYWEyMCIsImVtYWlsIjoibG9pc2dyaWZmaW5AZ21haWwuY29tIiwidXNlcm5hbWUiOiJMb2lzR3JpZmZpbiIsImlhdCI6MTc0NTY0MTkxMywiZXhwIjoxNzQ4MjMzOTEzfQ.F_eRz4sSZQNiy8_GwzXqpL6GNFd3vinggQKoi8tpfHI",
  "route": "CR-Newburyport",
  "station": "place-ER-0168"
}

###
GET  http://localhost:8081/favorites/680c621237f9cb990800aa27
Content-Type: application/json

###
DELETE http://localhost:8081/favorites/680c621237f9cb990800aa27
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MGM2MGUzMzdmOWNiOTkwODAwYWEyMCIsImVtYWlsIjoibG9pc2dyaWZmaW5AZ21haWwuY29tIiwidXNlcm5hbWUiOiJMb2lzR3JpZmZpbiIsImlhdCI6MTc0NTY0MTkxMywiZXhwIjoxNzQ4MjMzOTEzfQ.F_eRz4sSZQNiy8_GwzXqpL6GNFd3vinggQKoi8tpfHI"
}

### Get vehicles for a route
GET http://localhost:8081/api/vehicles/1
Content-Type: application/json

### Get trips for a route
GET http://localhost:8081/api/trips/67959825
Content-Type: application/json

### Get shape info by route ID
GET http://localhost:8081/api/shapes/933_0020
Content-Type: application/json

### Get all mbta routes
GET http://localhost:8081/api/routes/
Content-Type: application/json

### Get subway routes
GET http://localhost:8081/api/routes/1
Content-Type: application/json

### Get stops by route and date
GET http://localhost:8081/api/stops/2025-04-18/Orange
Content-Type: application/json

### Get all alerts
GET http://localhost:8081/api/alerts
Content-Type: application/json